name: deploy.yml

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/reusable-build-and-push.yml
    with:
      image_name: potenup/pg-core
      platforms: linux/amd64
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to PROD EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"
            docker pull potenup/pg-core:${{ needs.build.outputs.image_tag }}

            docker stop potenup || true
            docker rm potenup || true

            docker run -d \
              --name potenup \
              -p 8080:8080 \
              --restart always \
              potenup/pg-core:${{ needs.build.outputs.image_tag }}

            docker image prune -f
